spring:
  profiles:
    active: local
  application:
    name: ${APP_NAME}
  mongodb:
    uri: ${MONGODB_URI}
  data:
    mongodb:
      auto-index-creation: ${TRUE_OR_FALSE}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: ${TIMEOUT_MS}
security:
  bcrypt:
    strength: ${BCRYPT_STRENGTH}

jwt:
  secret: ${jwt.secret}
  access-expiry: ${jwt.access-expiry}
  refresh-expiry: ${jwt.refresh-expiry}
