spring:
  application:
    name: ${APP_NAME:Notes}
  mongodb:
    uri: ${SPRING_MONGODB_URI}
  data:
    mongodb:
      auto-index-creation: ${TRUE_OR_FALSE}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: ${TIMEOUT_MS}
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful
security:
  bcrypt:
    strength: ${BCRYPT_STRENGTH}

jwt:
  secret: ${JWT_SECRET}
  access-expiry: ${JWT_ACCESS_EXPIRY}
  refresh-expiry: ${JWT_REFRESH_EXPIRY}
resilience4j:
  ratelimiter:
    instances:
      authEndpoint:
        limit-for-period: 5
        limit-refresh-period: 1m
        timeout-duration: 0s
