spring:
  application:
    name: ${APP_NAME}
  mongodb:
    uri: ${MONGODB_URI}
  data:
    mongodb:
      auto-index-creation: ${TRUE_OR_FALSE}

security:
    bcrypt:
        strength: ${BCRYPT_STRENGTH}
